import { nowPageState, percentState, resultScoreState, scoreDataState } from '@/recoil/atom';
import Head from 'next/head'
import Link from 'next/link'
import { useEffect } from 'react';
import { useSetRecoilState } from 'recoil';

export default function Home() {

  const setNowPage = useSetRecoilState(nowPageState);
  const setPercent = useSetRecoilState(percentState);
  const setResultScore = useSetRecoilState(resultScoreState);
  const setScoreData = useSetRecoilState(scoreDataState);

  useEffect(()=>{
    setNowPage(0);
    setPercent(0);
    setResultScore("");
    setScoreData({ e: 0, i: 0, s: 0, n: 0, t: 0, f: 0 });
  },[])

  return (
    <>
      <Head>
        <title>Princess MBTI Type</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='wrap'>
        <div className='main'>
          <div className='background-top'>
            <div className='header'>
              <div className='container'>
                <div>
                  <span>나는 어떤 스타일의 공주일까?</span>
                  <h1 className='title'>공주유형테스트</h1>
                </div>
              </div>   
            </div>
            <div className='contents'>

            </div>
          </div>
          <div className='button'>
            <Link href={'/Main/page'}>
              <button type='button'>테스트 시작하기</button>
            </Link>
          </div>
        </div>
      </div>
    </>
  )
}
